
CREATE DATABASE divorce_law_firm_db;

USE divorce_law_firm_db;

/* GROUP 1: INDEPENDENT TABLES (NO FOREIGN KEYS) */

CREATE TABLE COURT 
(COURT_ID INT NOT NULL,
 JURISDICTION VARCHAR(255),
 PRIMARY KEY (COURT_ID));

CREATE TABLE CHILD
(CHILD_ID INT NOT NULL,
 NAME VARCHAR(255),
 DOB DATE,
 PRIMARY KEY (CHILD_ID)); 

CREATE TABLE FINANCIAL_DATA
(FINANCIAL_ID INT NOT NULL,
 PRIMARY KEY (FINANCIAL_ID)); 

CREATE TABLE LEGAL_TEAM
(LEGAL_ID INT NOT NULL,
 NAME VARCHAR(255),
 E_MAIL VARCHAR(255),
 PHONE_NR VARCHAR(20),
 HOURLY_RATE DOUBLE
  COMMENT 'HOURLY_RATE IN USD',
 PRIMARY KEY (LEGAL_ID)); 


/* GROUP 2: PRIMARY DEPENDENT TABLES */

CREATE TABLE CASE_RECORD
(DOCKET_NR INT NOT NULL,
TYPE ENUM('Divorce', 'Post-Judgment', 'Pre-Nup'),
 DATE_OF_MARRIAGE DATE,
 COURT_ID INT NOT NULL,
 PRIMARY KEY (DOCKET_NR),
 FOREIGN KEY (COURT_ID) REFERENCES COURT (COURT_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE ATTORNEY
(LEGAL_ID INT NOT NULL,
 JURIS_NO VARCHAR(50),
 PRIMARY KEY (LEGAL_ID),
 FOREIGN KEY (LEGAL_ID) REFERENCES LEGAL_TEAM (LEGAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE PARALEGAL
(LEGAL_ID INT NOT NULL,
 NOTARY_STATUS BOOLEAN,
 PRIMARY KEY (LEGAL_ID),
 FOREIGN KEY (LEGAL_ID) REFERENCES LEGAL_TEAM (LEGAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE SECRETARY
(LEGAL_ID INT NOT NULL,
PRIMARY KEY (LEGAL_ID),
 FOREIGN KEY (LEGAL_ID) REFERENCES LEGAL_TEAM (LEGAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE ASSET
(FINANCIAL_ID INT NOT NULL,
 NAME VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 VALUE DOUBLE,
 ACCOUNT_NR VARCHAR(50),
 OWNERSHIP_PRCT DOUBLE,
 PRIMARY KEY (FINANCIAL_ID),
 FOREIGN KEY (FINANCIAL_ID) REFERENCES FINANCIAL_DATA (FINANCIAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE LIABILITY
(FINANCIAL_ID INT NOT NULL,
 NAME VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 BALANCE DOUBLE,
 OWNERSHIP_PRCT DOUBLE,
 PRIMARY KEY (FINANCIAL_ID),
 FOREIGN KEY (FINANCIAL_ID) REFERENCES FINANCIAL_DATA (FINANCIAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE MONTHLY_EXPENSE
(FINANCIAL_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 COST DOUBLE,
 PRIMARY KEY (FINANCIAL_ID),
 FOREIGN KEY (FINANCIAL_ID) REFERENCES FINANCIAL_DATA (FINANCIAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 



/* GROUP 3: MULTI-LEVEL DEPENDENT TABLES */

CREATE TABLE PARTY
(PARTY_ID INT NOT NULL,
 NAME VARCHAR(255),
 SSN CHAR(11),
 DOB DATE,
 GENDER ENUM('F', 'M', 'O'),
 EMPLOYMENT_STATUS ENUM('Full-time', 'Part-time', 'Unemployed'),
 ANNUAL_INCOME DOUBLE,
 STATUS ENUM('Active', 'Inactive'),
 DOCKET_NR INT NOT NULL,
 PRIMARY KEY (PARTY_ID),
 FOREIGN KEY (DOCKET_NR) REFERENCES CASE_RECORD (DOCKET_NR)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE EVENTS
(EVENT_ID INT NOT NULL,
 TIME TIME,
 PLACE VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 DOCKET_NR INT NOT NULL,
 PRIMARY KEY (EVENT_ID),
 FOREIGN KEY (DOCKET_NR) REFERENCES CASE_RECORD (DOCKET_NR)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE BILLING
(BILL_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 TASK VARCHAR(255),
 FEE DOUBLE,
 DOCKET_NR INT NOT NULL,
 PRIMARY KEY (BILL_ID),
 FOREIGN KEY (DOCKET_NR) REFERENCES CASE_RECORD (DOCKET_NR)
  ON DELETE CASCADE ON UPDATE CASCADE); 



/* GROUP 4: ASSOCIATION / LINKING TABLES */

CREATE TABLE PARTY_CHILD
(PARTY_ID INT NOT NULL,
 CHILD_ID INT NOT NULL,
 PRIMARY KEY (PARTY_ID, CHILD_ID),
 FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (CHILD_ID) REFERENCES CHILD (CHILD_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE PARTY_FINANCIAL
(FINANCIAL_ID INT NOT NULL,
 PARTY_ID INT NOT NULL,
 PRIMARY KEY (FINANCIAL_ID, PARTY_ID),
 FOREIGN KEY (FINANCIAL_ID) REFERENCES FINANCIAL_DATA (FINANCIAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID)
  ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE GENERATES
(BILL_ID INT NOT NULL,
 LEGAL_ID INT NOT NULL,
 HOURS DOUBLE,
 PRIMARY KEY (BILL_ID, LEGAL_ID),
 FOREIGN KEY (BILL_ID) REFERENCES BILLING (BILL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (LEGAL_ID) REFERENCES LEGAL_TEAM (LEGAL_ID)
  ON DELETE CASCADE ON UPDATE CASCADE);
